# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(400, 300)
        self.tabWidget = QtWidgets.QTabWidget(dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 381, 281))
        self.tabWidget.setObjectName("tabWidget")
        self.current = QtWidgets.QWidget()
        self.current.setObjectName("current")
        self.label = QtWidgets.QLabel(self.current)
        self.label.setGeometry(QtCore.QRect(0, 0, 371, 251))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.current, "")
        self.daily = QtWidgets.QWidget()
        self.daily.setObjectName("daily")
        self.label_2 = QtWidgets.QLabel(self.daily)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 371, 251))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.daily, "")

        self.retranslateUi(dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Weather App"))
        self.label.setText(_translate("dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.current), _translate("dialog", "Current"))
        self.label_2.setText(_translate("dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.daily), _translate("dialog", "Daily"))